#!/bin/bash
# Generated by harbor_export.convert — Harbor verifier for the Repo2Run task.
# Replicates build_agent/tools/runtest.py / poetryruntest.py: rc=0 (tests
# collected/passed) or rc=5 (no tests in repo) is success; anything else
# is failure.

set -uo pipefail
mkdir -p /logs/verifier

if [ ! -d /repo ]; then
    echo "ERROR: /repo does not exist; environment Dockerfile did not clone repo." >&2
    echo 0 > /logs/verifier/reward.txt
    exit 0
fi

# Replay any env vars the agent exported during its session. The
# environment Dockerfile installs a PROMPT_COMMAND that snapshots
# `declare -px` after every interactive bash command, so the agent does
# not need to know anything about persistence — ordinary `export X=Y`
# calls are captured automatically. (This matches Repo2Run's persistent-
# shell semantics where agent exports persist into runtest.)
if [ -f /tmp/repo2run-env-snapshot ]; then
    # shellcheck disable=SC1091
    . /tmp/repo2run-env-snapshot 2>/dev/null || true
fi

# Snapshot may have captured an agent shell PATH that lost the Dockerfile's
# /root/.local/bin (where poetry installs). Re-prepend it so `poetry run …`
# is always findable.
export PATH="/root/.local/bin:$PATH"

cd /repo

# Detect poetry env (matches Repo2Run's heuristic in agents/configuration.py).
if [ -f poetry.lock ] || { [ -f pyproject.toml ] && grep -qF "[tool.poetry]" pyproject.toml; }; then
    PYTEST_CMD="poetry run pytest"
else
    PYTEST_CMD="pytest"
fi

echo "Running: $PYTEST_CMD --collect-only -q --disable-warnings"
echo

# shellcheck disable=SC2086
$PYTEST_CMD --collect-only -q --disable-warnings 2>&1 | tee /tmp/pytest.log
RC=${PIPESTATUS[0]}

echo
echo "pytest exit code: $RC"

# Repo2Run / paper EBSR: rc=0 or rc=5 -> success.
if [ "$RC" = "0" ] || [ "$RC" = "5" ]; then
    echo 1 > /logs/verifier/reward.txt
    echo "PASS (reward=1)"
else
    echo 0 > /logs/verifier/reward.txt
    echo "FAIL (reward=0)"
fi

exit 0
